require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/metrics", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Metric. As you add validations to Metric, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Metric.create! valid_attributes
      get metrics_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      metric = Metric.create! valid_attributes
      get metric_url(metric)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_metric_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      metric = Metric.create! valid_attributes
      get edit_metric_url(metric)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Metric" do
        expect {
          post metrics_url, params: { metric: valid_attributes }
        }.to change(Metric, :count).by(1)
      end

      it "redirects to the created metric" do
        post metrics_url, params: { metric: valid_attributes }
        expect(response).to redirect_to(metric_url(Metric.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Metric" do
        expect {
          post metrics_url, params: { metric: invalid_attributes }
        }.to change(Metric, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post metrics_url, params: { metric: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested metric" do
        metric = Metric.create! valid_attributes
        patch metric_url(metric), params: { metric: new_attributes }
        metric.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the metric" do
        metric = Metric.create! valid_attributes
        patch metric_url(metric), params: { metric: new_attributes }
        metric.reload
        expect(response).to redirect_to(metric_url(metric))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        metric = Metric.create! valid_attributes
        patch metric_url(metric), params: { metric: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested metric" do
      metric = Metric.create! valid_attributes
      expect {
        delete metric_url(metric)
      }.to change(Metric, :count).by(-1)
    end

    it "redirects to the metrics list" do
      metric = Metric.create! valid_attributes
      delete metric_url(metric)
      expect(response).to redirect_to(metrics_url)
    end
  end
end
